### PR TITLE
Beta Version 1.1

### PR DESCRIPTION
**Pull request by RhinosF1**
Changelog

*enables editing of realname and ident
*makes quotebot calculate quote numbers itself
*adds quotebot to pm

### CODE REVIEW

**Comment by sario528** [comment]
Re-opening PR as beta v-1.1 is back in active development.

**Review by RhinosF1 — COMMENTED** [review]
L2-3 on settings.csv should have ; at the end

**Review by RhinosF1 — COMMENTED** [review]
LGTM, I’d credit yourself in setup.py though

**Review by sario528 — APPROVED** [review]
Things slowed down for a bit, but we're back on track.

**Pull request merged**
