### PR TITLE
Dev 0 Rewrite

### PR DESCRIPTION
**Pull request by RhinosF1**
PR for changing names over to new name

### CODE REVIEW

**Comment by RhinosF1** [comment]
Waiting on #8 been done before pushing this

**Comment by RhinosF1** [comment]
Please review - Deleting the examples is intentional

**Review by RhinosF1 — COMMENTED** [review]
Happy with all other changes

**Review by paladox — APPROVED** [review]

**Comment by RhinosF1** [comment]
Removing @dschultzdev as a reviewer given I'm pretty confident and @paladox has checked it I'm merging this

**Pull request merged**
